stdint and zmq packages
whitequark/opam-android pull request #33
Opened 2017-05-26 10:31 UTC by mryau

2017-05-26 10:54 UTC, whitequark requested changes

2017-05-26 10:54 UTC, whitequark commented on packages/stdint-android.0.3.0/opam
> +  "base-bytes"
Implied in ocaml-android

2017-05-26 10:54 UTC, whitequark commented on packages/stdint-android.0.3.0/opam
> +  "ocamlfind" {>= "1.5"}
Implied in ocaml-android

2017-05-26 10:54 UTC, whitequark commented on packages/zmq-android.4.0-8/findlib
> +zmq
Not needed as opam does not know about `-toolchain`

2017-05-26 10:54 UTC, whitequark commented on packages/stdint-android.0.3.0/findlib
> +stdint
Not needed as opam does not know about `-toolchain`

2017-05-26 10:54 UTC, whitequark commented on packages/zmq-android.4.0-8/opam
> +  "ocamlfind"
Implied in ocaml-android

2017-05-26 10:54 UTC, whitequark commented on packages/zmq-android.4.0-8/opam
> +  "base-unix"
Implied in ocaml-android

2017-05-26 10:54 UTC, whitequark commented on packages/zmq-android.4.0-8/opam
> +  "ocaml-zmq"
I don't see a reason for this conflict

2017-05-26 10:54 UTC, whitequark commented on packages/conf-zmq-android.0.1/descr
> +Virtual package relying on zmq library installation.
We do not use virtual packages for native dependencies in cross-toolchains

2017-05-26 10:54 UTC, whitequark commented on packages/zmq-android.4.0-8/opam
> +  "conf-zmq-android"
Instead of this dependency, you should add a depext for the zmq package in MXE

2017-05-26 11:07 UTC, mryau commented on packages/zmq-android.4.0-8/findlib
> +zmq
Hello,

without such findlib files for _zmq-android_ and _stdint_, ocamlfind can't find this packages when I compile my code.

2017-05-26 11:07 UTC, mryau commented on packages/zmq-android.4.0-8/opam
> +  "conf-zmq-android"
Is MXE means http://mxe.cc/ ?
I don't use android-ndk -- I'm sit on yocto/bitbake with plain gcc cross-compiler suite, so I can't use it.

2017-05-26 11:08 UTC, mryau commented on packages/zmq-android.4.0-8/opam
> +  "ocaml-zmq"
I'm steal this opam file from author of package, and it modified it.

2017-05-26 11:15 UTC, whitequark commented on packages/zmq-android.4.0-8/opam
> +  "conf-zmq-android"
Sorry, MXE is not relevant, forget this part.

2017-05-26 12:15 UTC, whitequark commented on packages/zmq-android.4.0-8/findlib
> +zmq
That doesn't make any sense, ocamlfind does not use these "findlib" files. Are you sure there was no other difference? Can you check one more time please?

2017-05-27 01:29 UTC, whitequark commented on packages/zmq-android.4.0-8/findlib
> +zmq
There are no findlib files in opam-repository anymore. https://github.com/ocaml/opam-repository/pull/9328

2017-05-31 08:59 UTC, mryau commented on packages/zmq-android.4.0-8/findlib
> +zmq
Yes, I remove them too -- on clear installation I don't seen problems without _findlib_ files.

2026-08-09 14:54 UTC, closed without merging